import { useState, type FormEvent } from 'react';
import { ArrowDown, ArrowRight, Check, ChevronDown, Mail, Menu, Phone, Send, X } from 'lucide-react';
import Navbar from './components/Navbar';
import AboutSection from './components/AboutSection';
import FeaturesSection from './components/FeaturesSection';

const mistakes=[
 ['01','Неправильно определяют цену','Завышенная цена отпугивает покупателей. Заниженная — сразу уменьшает сумму сделки. Цена должна опираться на рынок и стратегию продажи.'],
 ['02','Слабое объявление','Фото, заголовок и описание формируют первое впечатление. Если объявление не вызывает интерес, до показа покупатель не дойдёт.'],
 ['03','Теряют обращения','Пропущенный звонок или поздний ответ — это потенциально потерянный покупатель. Важно фиксировать обращения и быстро возвращаться к каждому.'],
 ['04','Проводят показы без цели','Показ должен вести к следующему шагу: обратной связи, переговорам или авансу. Просто показать квартиру недостаточно.'],
 ['05','Торгуются слишком рано','Скидка должна быть частью переговоров, а не автоматической реакцией на первое предложение покупателя.'],
];
const faqs=[
 ['Можно ли продать квартиру самостоятельно?','Да. Для этого важно понимать последовательность действий: подготовка, цена, упаковка, поиск покупателей, показы, переговоры и сделка.'],
 ['Зачем нужна система из 20 этапов?','Чтобы не собирать процесс по кусочкам. Каждый этап отвечает на конкретный вопрос и переводит продавца к следующему действию.'],
 ['Нужно ли размещать объявление только на одной площадке?','В текущей системе предусмотрена работа с несколькими площадками и оценка результата продвижения.'],
 ['Что делать, если покупатели звонят, но не покупают?','Нужно анализировать повторяющиеся возражения, качество показов, позиционирование и цену, а затем корректировать стратегию.'],
];

export default function App(){
 const [videoOpen,setVideoOpen]=useState(false); const [form,setForm]=useState({name:'',phone:'',message:''}); const [sent,setSent]=useState(false); const [sending,setSending]=useState(false);
 async function submit(e:FormEvent){e.preventDefault();setSending(true);try{const r=await fetch('https://formsubmit.co/ajax/danil@avreal.ru',{method:'POST',headers:{'Content-Type':'application/json','Accept':'application/json'},body:JSON.stringify({...form,_subject:'Новая заявка с сайта «Продай сам»',_template:'table'})});if(!r.ok)throw new Error();setSent(true);setForm({name:'',phone:'',message:''});}catch{setSent(false);alert('Не удалось отправить заявку. Позвоните или напишите в Telegram.')}finally{setSending(false)}}
 return <div id="top" className="bg-[#f4f7f5] text-[#102622]">
   <section className="relative mb-[-25px] h-screen min-h-[680px] overflow-hidden bg-[#050f1d]">
     <div className="absolute inset-0"><img src="https://raw.githubusercontent.com/dancheei2-hue/prodazha/main/desk.png" alt="Продажа квартиры" className="h-full w-full object-cover"/><div className="absolute inset-0 bg-black/20"/><div className="absolute inset-0 bg-gradient-to-t from-[#050f1d]/95 via-[#050f1d]/20 to-transparent"/></div>
     <Navbar/>
     <div className="relative z-10 mx-auto flex h-full max-w-[1180px] flex-col justify-end px-5 pb-12 text-center md:px-10 md:pb-16 lg:px-16">
       <p className="eyebrow mb-4 text-white/55">БЕСПЛАТНАЯ СИСТЕМА ПРОДАЖИ</p>
       <h1 className="text-5xl font-normal leading-[1.05] tracking-[-.045em] text-white sm:text-7xl md:text-8xl lg:text-[96px]">Продайте квартиру<br/><span className="text-[#78a9ff]">самостоятельно</span></h1>
       <p className="mx-auto mt-6 max-w-[520px] text-sm font-medium leading-relaxed text-white/75 md:text-base">Пошаговая система, которая помогает пройти путь от подготовки квартиры до сделки без лишней суеты.</p>
       <div className="mx-auto mt-7 flex w-fit max-w-full items-center gap-4 rounded-xl bg-black/25 py-1 pl-4 pr-1 backdrop-blur-md sm:pl-6"><span className="hidden text-sm font-medium text-white sm:inline">20 этапов. Понятные действия. Один чек-лист.</span><span className="text-sm font-medium text-white sm:hidden">20 этапов. Понятно по шагам.</span><a href="stages.html" className="shrink-0 rounded-xl bg-white px-5 py-2.5 text-sm font-medium text-black transition hover:bg-white/90">Начать</a></div>
       <a href="#about" className="mx-auto mt-8 grid h-9 w-9 place-items-center rounded-full border border-white/25 text-white/80"><ArrowDown className="h-4 w-4"/></a>
     </div>
   </section>

   <AboutSection/>

   <FeaturesSection/>

   <section id="mistakes" className="bg-white px-5 py-20 md:px-10 md:py-32 lg:px-16">
    <div className="mx-auto max-w-[1180px]"><p className="eyebrow text-[#0164ff]">ВАЖНО ЗНАТЬ</p><div className="mt-4 flex flex-col justify-between gap-8 md:flex-row md:items-end"><h2 className="max-w-2xl text-3xl font-normal leading-[1.12] tracking-tight md:text-5xl">Где продавцы чаще всего теряют деньги?</h2><p className="max-w-sm text-sm leading-relaxed text-[#52625e]">Пять моментов, где решение продавца напрямую влияет на результат продажи.</p></div>
    <div className="mt-12 grid gap-3">{mistakes.map(([n,t,d],i)=><article key={n} className={`group grid gap-5 rounded-3xl border border-[#d8e2df] p-6 transition duration-500 hover:-translate-y-1 md:grid-cols-[80px_1fr_2fr] md:items-start md:p-8 ${i===0?'bg-[#eaf3fe]':''}`}><span className="text-sm font-medium text-[#0164ff]">{n}</span><h3 className="text-xl font-medium tracking-tight">{t}</h3><p className="text-sm leading-relaxed text-[#52625e] md:text-base">{d}</p></article>)}</div></div>
   </section>

   <section className="bg-[#f4f7f5] px-5 py-20 md:px-10 md:py-32 lg:px-16"><div className="mx-auto max-w-[1180px]"><p className="eyebrow text-[#0164ff]">20 ЭТАПОВ</p><div className="grid gap-12 lg:grid-cols-[.8fr_1.2fr] lg:items-start"><div><h2 className="mt-4 text-3xl font-normal leading-[1.12] tracking-tight md:text-5xl">Вся продажа — перед вами</h2><p className="mt-5 max-w-md text-sm leading-relaxed text-[#52625e]">От цели и документов до переговоров, договора и передачи квартиры. Один маршрут вместо десятков разрозненных советов.</p><a href="stages.html" className="btn btn-blue mt-7">Открыть все 20 этапов <ArrowRight className="ml-2 h-4 w-4"/></a></div><div className="grid gap-2">{[['01–05','Подготовка'],['06–10','Поиск покупателя'],['11–15','Показы и переговоры'],['16–20','Сделка']].map(([num,title])=><a key={num} href={`stages.html#stage-${num.slice(0,2).replace('–','')}`} className="group flex items-center gap-5 rounded-2xl bg-white p-5 transition hover:-translate-y-0.5"><span className="text-xs font-medium text-[#0164ff]">{num}</span><span className="flex-1 font-medium">{title}</span><ArrowRight className="h-4 w-4 text-[#0164ff] transition group-hover:translate-x-1"/></a>)}</div></div></div></section>

   <section className="bg-white px-5 py-20 md:px-10 md:py-32 lg:px-16"><div className="mx-auto max-w-[1180px]"><p className="eyebrow text-[#0164ff]">ЧТО ДЕЛАТЬ ДАЛЬШЕ?</p><h2 className="mt-4 max-w-2xl text-3xl font-normal leading-[1.12] tracking-tight md:text-5xl">Выберите свой путь</h2><div className="mt-10 grid gap-4 lg:grid-cols-3"><article className="rounded-3xl border border-[#d8e2df] p-7"><span className="text-xs text-[#0164ff]">01</span><h3 className="mt-10 text-xl font-medium">Изучить систему</h3><p className="mt-3 text-sm leading-relaxed text-[#52625e]">20 этапов продажи, чтобы последовательно пройти весь процесс самостоятельно.</p><a href="stages.html" className="mt-6 inline-flex items-center text-sm font-medium text-[#0164ff]">Перейти к этапам <ArrowRight className="ml-2 h-4 w-4"/></a></article><article className="rounded-3xl border border-[#d8e2df] bg-[#eaf3fe] p-7"><span className="text-xs text-[#0164ff]">02</span><h3 className="mt-10 text-xl font-medium">Разобрать ситуацию</h3><p className="mt-3 text-sm leading-relaxed text-[#52625e]">Ответьте на вопросы о квартире и получите направление, с чего начать именно сейчас.</p><a href="#contact" className="mt-6 inline-flex items-center text-sm font-medium text-[#0164ff]">Пройти разбор <ArrowRight className="ml-2 h-4 w-4"/></a></article><article className="rounded-3xl bg-[#050f1d] p-7 text-white"><span className="text-xs text-[#8eb9ff]">03</span><h3 className="mt-10 text-xl font-medium">Передать продажу специалисту</h3><p className="mt-3 text-sm leading-relaxed text-white/60">Если не хотите заниматься продажей самостоятельно, обсудите её со специалистом Самолет Плюс.</p><a href="#contact" className="mt-6 inline-flex items-center text-sm font-medium text-[#8eb9ff]">Обсудить продажу <ArrowRight className="ml-2 h-4 w-4"/></a></article></div></div></section>

   <section id="faq" className="bg-[#f4f7f5] px-5 py-20 md:px-10 md:py-32 lg:px-16"><div className="mx-auto max-w-[900px]"><p className="eyebrow text-[#0164ff]">FAQ</p><h2 className="mt-4 text-3xl font-normal md:text-5xl">Частые вопросы</h2><div className="mt-10 space-y-3">{faqs.map(([q,a])=><details key={q} className="group rounded-2xl bg-white px-6"><summary className="flex cursor-pointer list-none items-center justify-between py-5 text-sm font-medium md:text-base"><span>{q}</span><ChevronDown className="h-5 w-5 shrink-0 text-[#0164ff] transition group-open:rotate-180"/></summary><p className="max-w-3xl pb-6 text-sm leading-relaxed text-[#52625e]">{a}</p></details>)}</div></div></section>

   <section id="contact" className="bg-[#050f1d] px-5 py-20 text-white md:px-10 md:py-32 lg:px-16"><div className="mx-auto grid max-w-[1180px] gap-12 lg:grid-cols-[.8fr_1.2fr] lg:items-start"><div><p className="eyebrow text-[#8eb9ff]">КОНТАКТЫ</p><h2 className="mt-4 text-4xl font-normal leading-tight md:text-6xl">Если хотите обсудить продажу — напишите</h2><div className="mt-8 space-y-3 text-sm text-white/70"><a href="tel:+79512002182" className="flex items-center gap-3 hover:text-white"><Phone className="h-4 w-4"/>+7 951 200-21-82</a><a href="https://t.me/averin_creative" className="flex items-center gap-3 hover:text-white"><Send className="h-4 w-4"/>Telegram</a><a href="mailto:Danil@avreal.ru" className="flex items-center gap-3 hover:text-white"><Mail className="h-4 w-4"/>Danil@avreal.ru</a></div></div><form onSubmit={submit} className="rounded-3xl bg-white p-5 text-[#102622] md:p-8"><div className="grid gap-4"><label className="text-xs font-medium">Имя<input required value={form.name} onChange={e=>setForm({...form,name:e.target.value})} className="mt-2 w-full rounded-xl bg-[#f4f7f5] px-4 py-3 outline-none ring-[#0164ff] focus:ring-2" placeholder="Как к вам обращаться?"/></label><label className="text-xs font-medium">Телефон<input required value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})} className="mt-2 w-full rounded-xl bg-[#f4f7f5] px-4 py-3 outline-none ring-[#0164ff] focus:ring-2" placeholder="+7 ..."/></label><label className="text-xs font-medium">Комментарий<textarea value={form.message} onChange={e=>setForm({...form,message:e.target.value})} rows={4} className="mt-2 w-full resize-none rounded-xl bg-[#f4f7f5] px-4 py-3 outline-none ring-[#0164ff] focus:ring-2" placeholder="Что хотите обсудить?"/></label><button disabled={sending} className="btn btn-blue w-full">{sending?'Отправляем…':sent?'Заявка отправлена':'Отправить заявку'} <ArrowRight className="ml-2 h-4 w-4"/></button></div></form></div></section>
   <footer className="bg-[#050f1d] px-5 pb-8 text-white/45 md:px-10 lg:px-16"><div className="mx-auto flex max-w-[1180px] flex-col justify-between gap-3 border-t border-white/10 pt-6 text-xs md:flex-row"><span>ПРОДАЙ САМ · Данил Аверин</span><span>Система самостоятельной продажи недвижимости</span></div></footer>

   {videoOpen&&<div className="fixed inset-0 z-[100] grid place-items-center bg-black/80 p-4" onClick={()=>setVideoOpen(false)}><div className="w-full max-w-3xl overflow-hidden rounded-3xl bg-black" onClick={e=>e.stopPropagation()}><div className="flex items-center justify-between px-4 py-3 text-white"><span className="text-sm">Как устроена продажа квартиры</span><button onClick={()=>setVideoOpen(false)}><X className="h-5 w-5"/></button></div><div className="aspect-video bg-[#151f2b] grid place-items-center"><p className="text-sm text-white/60">Здесь можно подключить ваше видео</p></div></div></div>}
 </div>
}
